using System.Drawing;

namespace Severino.Tests.App;

/// <summary>The .ico generated by scripts/build-icons.cs, as Windows reads it.</summary>
public sealed class AppIconTests
{
    private static readonly string Assets = Path.Combine(RepoRoot(), "src", "Severino.App", "Assets");
    private static readonly string IconPath = Path.Combine(Assets, "severino.ico");

    /// <summary>The sizes TrayService asks for: the small-icon size at 100% to 200% DPI, and more.</summary>
    [Theory]
    [InlineData(16)]
    [InlineData(20)]
    [InlineData(24)]
    [InlineData(32)]
    [InlineData(48)]
    public void Has_a_frame_drawn_for_each_tray_size(int size)
    {
        using var icon = new Icon(IconPath, size, size);
        using var bitmap = icon.ToBitmap();

        Assert.Equal(size, icon.Width);
        // Transparent corners and a fully opaque middle: the mascot, with nothing showing through.
        Assert.Equal(0, bitmap.GetPixel(0, 0).A);
        Assert.Equal(255, bitmap.GetPixel(size / 2, size / 2).A);
    }

    /// <summary>The tray states: the badge and the grey must be drawn at each size, not scaled down.</summary>
    [Theory]
    [InlineData("severino-alert.ico", 16)]
    [InlineData("severino-alert.ico", 24)]
    [InlineData("severino-alert.ico", 32)]
    [InlineData("severino-paused.ico", 16)]
    [InlineData("severino-paused.ico", 24)]
    [InlineData("severino-paused.ico", 32)]
    public void Tray_states_have_their_own_frames(string file, int size)
    {
        using var icon = new Icon(Path.Combine(Assets, file), size, size);
        using var bitmap = icon.ToBitmap();
        var corner = bitmap.GetPixel(size - 1 - size / 8, size - 1 - size / 8);

        Assert.Equal(size, icon.Width);
        if (file.Contains("alert"))
            Assert.True(corner.R > 180 && corner.G < 90, $"expected the red badge, got {corner}");
        else
            Assert.All(Enumerable.Range(0, size).Select(x => bitmap.GetPixel(x, size / 2)), p => Assert.True(p.R == p.G && p.G == p.B, $"not grey: {p}"));
    }

    [Fact]
    public void Has_a_256_frame_for_the_shell()
    {
        // System.Drawing ignores the 256 frame (its width is stored as 0), so read the directory.
        using var reader = new BinaryReader(File.OpenRead(IconPath));
        reader.ReadInt16();
        Assert.Equal(1, reader.ReadInt16());
        var count = reader.ReadInt16();
        var widths = Enumerable.Range(0, count).Select(_ =>
        {
            var width = reader.ReadByte();
            reader.ReadBytes(15);
            return width == 0 ? 256 : width;
        });

        Assert.Contains(256, widths);
    }

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Severino.slnx")))
            dir = dir.Parent;
        return dir?.FullName ?? throw new InvalidOperationException("Severino.slnx not found above the test output.");
    }
}
