using System.Drawing;

namespace Severino.Tests.App;

/// <summary>The .ico generated by scripts/build-icons.cs, as Windows reads it.</summary>
public sealed class AppIconTests
{
    private static readonly string IconPath = Path.Combine(RepoRoot(), "src", "Severino.App", "Assets", "severino.ico");

    /// <summary>The sizes TrayService asks for: the small-icon size at 100% to 200% DPI, and more.</summary>
    [Theory]
    [InlineData(16)]
    [InlineData(20)]
    [InlineData(24)]
    [InlineData(32)]
    [InlineData(48)]
    public void Has_a_frame_drawn_for_each_tray_size(int size)
    {
        using var icon = new Icon(IconPath, size, size);
        using var bitmap = icon.ToBitmap();

        Assert.Equal(size, icon.Width);
        // Transparent corners and a fully opaque middle: the mascot, with nothing showing through.
        Assert.Equal(0, bitmap.GetPixel(0, 0).A);
        Assert.Equal(255, bitmap.GetPixel(size / 2, size / 2).A);
    }

    [Fact]
    public void Has_a_256_frame_for_the_shell()
    {
        // System.Drawing ignores the 256 frame (its width is stored as 0), so read the directory.
        using var reader = new BinaryReader(File.OpenRead(IconPath));
        reader.ReadInt16();
        Assert.Equal(1, reader.ReadInt16());
        var count = reader.ReadInt16();
        var widths = Enumerable.Range(0, count).Select(_ =>
        {
            var width = reader.ReadByte();
            reader.ReadBytes(15);
            return width == 0 ? 256 : width;
        });

        Assert.Contains(256, widths);
    }

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "Severino.slnx")))
            dir = dir.Parent;
        return dir?.FullName ?? throw new InvalidOperationException("Severino.slnx not found above the test output.");
    }
}
