<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Severino.Core\Severino.Core.csproj" />
    <ProjectReference Include="..\..\src\Severino.Contracts\Severino.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Severino.Helper\Severino.Helper.csproj" />
  </ItemGroup>

</Project>
